export const SUPABASE_URL = 'https://xmxyfapmlvaypvyfdloa.supabase.co';
export const SUPABASE_KEY =
	'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhteHlmYXBtbHZheXB2eWZkbG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDY2MjAyNjIsImV4cCI6MjAyMjE5NjI2Mn0.MJL6WAol7qRHuz__G9gyG2s1lz6Ua1uQq2Iibdr1fJc';
